language: python
python:
  - "3.8"
  - "3.8-dev"
  - "3.9"
  - "3.9-dev"
  - "3.10"
  - "3.10-dev"
  - "3.11"
  - "3.11-dev"
  - "3.12"
  - "3.12-dev"
  - "3.13"
  - "3.13-dev"
  - "3.13.1"

install:
  - python setup.py install
script:
  - python setup.py check
